# Generated by Django 5.1 on 2024-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objmodel',
            name='obj_file',
        ),
        migrations.RemoveField(
            model_name='objmodel',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='objmodel',
            name='file',
            field=models.FileField(default=1, upload_to='models/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
